spring:
  profiles:
    active: dev #激活开发环境配置
    

server:
  port: 4001
spring:
  profiles: dev #开发环境
  applications:
    name: micrsoervice-config-dev
    


server:
  port: 4002
spring:
  profiles: prod #生产环境
  applications:
    name: microservice-config-prod
